apiVersion: v1
kind: ServiceAccount
metadata:
  name: wai-pingfederate
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vault.authServiceAccount }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
