apiVersion: v1
kind: Service
metadata:
  name: wai-pingfederate-admin
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wai-pingfederate
    app.kubernetes.io/instance: isolated-13-1
  ports:
    - name: admin-https
      port: 9999
      targetPort: admin-https
---
apiVersion: v1
kind: Service
metadata:
  name: wai-pingfederate-engine
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wai-pingfederate
    app.kubernetes.io/instance: isolated-13-1
  ports:
    - name: engine-https
      port: 9031
      targetPort: engine-https
