apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: wai-pingauthorize
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wai-pingauthorize
      app.kubernetes.io/instance: isolated-11-1
