apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wai-strict
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: wai-strict
  source:
    repoURL: https://github.com/darkedges/pf-tts.git
    targetRevision: feature/helm
    path: deploy/helm/wai-strict
    helm:
      releaseName: wai-strict
      valueFiles:
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wai-strict
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
