apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wai-strict
  namespace: argocd
spec:
  description: Strict WAI Transaction Token call chain
  sourceRepos:
    - https://github.com/darkedges/pf-tts.git
  destinations:
    - namespace: wai-strict
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: networking.k8s.io
      kind: Ingress
    - group: secrets.hashicorp.com
      kind: VaultConnection
    - group: secrets.hashicorp.com
      kind: VaultAuth
    - group: secrets.hashicorp.com
      kind: VaultStaticSecret
