namespace: wai-pingfederate
images:
  runtime: docker.io/darkedges/pf-tts-pingfederate@sha256:c0871f8ccfcf4b4ef28200d2ce9a1b65a979b83a35e2654669b19383b38c0bd9
profile:
  branch: feature/kubernetes-pf13
storage:
  size: 8Gi
  storageClassName: hostpath
vault:
  address: https://vault.internal.darkedges.com
  connectionName: wai-pingfederate-vault
  caCertSecretRef: wai-vault-server-ca
  authName: wai-pingfederate-vault-auth
  authServiceAccount: wai-pingfederate-vault-auth
  role: wai-pingfederate-13-1
  audience: vault
  kubernetesMount: kubernetes
  kvMount: kv
  refreshAfter: 5m
resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: "2"
    memory: 4Gi
